### ISSUE TITLE
Evidence aut

### ISSUE THREAD

**Issue by blannik** [blannik/pythonProject#5]
Ahoj, prosím o kontrolu.
Díky
Blanka

**Comment by lutydlitatova** [comment]
@blannik 

Ahoj, nevidím nikde nový soubor, zkontroluješ prosím radši, jestli ti prošel `git push` ? Případně pošli odkaz, možná jsem to přehlédla.

Díky 🙂

**Comment by blannik** [comment]
ahoj, omylem jsem z toho vytvořila novou větev - ten přenos mezi pycharm a github mi pořád ještě moc nejde. Odkaz je tady: https://github.com/blannik/pythonProject/blob/Lekce_3/Domaci_ukoly/Lekce_3/01_Evidence_aut.py
Díky
B

**Comment by lutydlitatova** [comment]
Super řešení! 👍
